// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InsuranceQuoteTestSuiteTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void insuranceQuote01ValidDataNoAccidents() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Oluwatosin");
    driver.FindElement(By.Id("lastName")).SendKeys("Adeniyi");
    driver.FindElement(By.Id("address")).SendKeys("155 king St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2J 0E8");
    driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
    driver.FindElement(By.Id("email")).SendKeys("tosin.adeniyi@gmail.com");
    driver.FindElement(By.Id("age")).SendKeys("25");
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.CssSelector("body")).Click();
  }
  [Test]
  public void insuranceQuote02ValidDataTwoAccidents() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("David");
    driver.FindElement(By.Id("lastName")).SendKeys("Michael");
    driver.FindElement(By.Id("address")).SendKeys("156 King St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2E 0E8");
    driver.FindElement(By.Id("phone")).SendKeys("123-456-1234");
    driver.FindElement(By.Id("email")).SendKeys("david.michael@gmail.com");
    driver.FindElement(By.Id("age")).SendKeys("25");
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.Id("accidents")).SendKeys("2");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote03ValidDataFourAccidents() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Debbie");
    driver.FindElement(By.Id("lastName")).SendKeys("Charles");
    driver.FindElement(By.Id("address")).SendKeys("157 King St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2E 0F8");
    driver.FindElement(By.Id("phone")).SendKeys("123-456-7890");
    driver.FindElement(By.Id("email")).SendKeys("debbie.charles@gmail.com");
    driver.FindElement(By.Id("age")).SendKeys("35");
    driver.FindElement(By.Id("experience")).SendKeys("10");
    driver.FindElement(By.Id("accidents")).SendKeys("4");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote04InvalidPhoneNumber() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Jane");
    driver.FindElement(By.Id("lastName")).SendKeys("Smith");
    driver.FindElement(By.Id("address")).SendKeys("159 King St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2J 0E9");
    driver.FindElement(By.Id("phone")).SendKeys("123");
    driver.FindElement(By.Id("email")).SendKeys("jane.smith@gmail.com");
    driver.FindElement(By.Id("age")).SendKeys("27");
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote05InvalidEmail() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Comfort");
    driver.FindElement(By.Id("lastName")).SendKeys("Rick");
    driver.FindElement(By.Id("address")).SendKeys("161 King St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2E 2S7");
    driver.FindElement(By.Id("phone")).SendKeys("123-678-2345");
    driver.FindElement(By.Id("email")).SendKeys("comfort.rick");
    driver.FindElement(By.Id("age")).SendKeys("28");
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote07OmittedAge() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Cane");
    driver.FindElement(By.Id("lastName")).SendKeys("Abel");
    driver.FindElement(By.Id("address")).SendKeys("163 king St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2E 0E9");
    driver.FindElement(By.Id("phone")).SendKeys("432-124-0985");
    driver.FindElement(By.Id("email")).SendKeys("cane.abel@gmail.com");
    driver.FindElement(By.Id("experience")).SendKeys("5");
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote08OmittedAccidents() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Lizzy");
    driver.FindElement(By.Id("lastName")).SendKeys("Jones");
    driver.FindElement(By.Id("address")).SendKeys("165 king St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2D 2S7");
    driver.FindElement(By.Id("phone")).SendKeys("123-465-8790");
    driver.FindElement(By.Id("email")).SendKeys("lizzy.jones@gmail.com");
    driver.FindElement(By.Id("age")).SendKeys("37");
    driver.FindElement(By.Id("experience")).SendKeys("8");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote06InvalidPostalCode() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Eve");
    driver.FindElement(By.Id("lastName")).SendKeys("Adam");
    driver.FindElement(By.Id("address")).SendKeys("162 king St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2J0E");
    driver.FindElement(By.Id("phone")).SendKeys("123-456-2345");
    driver.FindElement(By.Id("email")).SendKeys("eve.adam@gmail.com");
    driver.FindElement(By.Id("age")).SendKeys("35");
    driver.FindElement(By.Id("experience")).SendKeys("17");
    driver.FindElement(By.Id("accidents")).SendKeys("1");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote09OmittedExperience() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Michael");
    driver.FindElement(By.Id("lastName")).SendKeys("Jackson");
    driver.FindElement(By.Id("address")).SendKeys("166 king St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2O 2S6");
    driver.FindElement(By.Id("phone")).SendKeys("654-123-6789");
    driver.FindElement(By.Id("email")).SendKeys("michael.jackson@gmail.com");
    driver.FindElement(By.Id("age")).SendKeys("45");
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote10ValidAgeHighExperienceNoAccidents() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("John");
    driver.FindElement(By.Id("lastName")).SendKeys("Mark");
    driver.FindElement(By.Id("address")).SendKeys("168 king St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2D 2G1");
    driver.FindElement(By.Id("phone")).SendKeys("123-321-1234");
    driver.FindElement(By.Id("email")).SendKeys("john.mark@gmail");
    driver.FindElement(By.Id("age")).SendKeys("45");
    driver.FindElement(By.Id("experience")).SendKeys("20");
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote11ValidDataZeroExperienceNoAccidents() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Crystal");
    driver.FindElement(By.Id("lastName")).SendKeys("Mark");
    driver.FindElement(By.Id("address")).SendKeys("169 King st");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("M20 0F3");
    driver.FindElement(By.Id("phone")).SendKeys("423-456-6789");
    driver.FindElement(By.Id("email")).SendKeys("crystal.mark@gmail.com");
    driver.FindElement(By.Id("age")).SendKeys("18");
    driver.FindElement(By.Id("experience")).SendKeys("0");
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("postalCode")).SendKeys("M2J 0F3");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote12ValidAgeValidExperienceThreeAccidents() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Anne ");
    driver.FindElement(By.Id("lastName")).SendKeys("David");
    driver.FindElement(By.Id("address")).SendKeys("154 King St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2J 0E8");
    driver.FindElement(By.Id("phone")).SendKeys("123-454-0908");
    driver.FindElement(By.Id("email")).SendKeys("anne.david@gmail.com");
    driver.FindElement(By.Id("age")).SendKeys("30");
    driver.FindElement(By.Id("experience")).SendKeys("10");
    driver.FindElement(By.Id("accidents")).SendKeys("3");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote13ValidPostalCodeSpecialCases() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Edward");
    driver.FindElement(By.Id("lastName")).SendKeys("James");
    driver.FindElement(By.Id("address")).SendKeys("153 King St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2J 0E9");
    driver.FindElement(By.Id("phone")).SendKeys("346-657-9843");
    driver.FindElement(By.Id("email")).SendKeys("edward.james@gmail.com");
    driver.FindElement(By.Id("age")).SendKeys("38");
    driver.FindElement(By.Id("experience")).SendKeys("8");
    driver.FindElement(By.Id("accidents")).SendKeys("1");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote14InvalidExperienceAgeConstraint() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Sophia");
    driver.FindElement(By.Id("lastName")).SendKeys("Brown");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2J 0E6");
    driver.FindElement(By.Id("phone")).SendKeys("213-435-3567");
    driver.FindElement(By.Id("email")).SendKeys("sophia.brown@gmail.com");
    driver.FindElement(By.Id("age")).SendKeys("50");
    driver.FindElement(By.Id("experience")).SendKeys("40");
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("address")).SendKeys("151 King St");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
  [Test]
  public void insuranceQuote15OmittedAddressValidData() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
    driver.FindElement(By.Id("firstName")).SendKeys("Vanessa");
    driver.FindElement(By.Id("lastName")).SendKeys("Queen");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("150 King St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2J 0E4");
    driver.FindElement(By.Id("phone")).SendKeys("435-678-321");
    driver.FindElement(By.Id("email")).SendKeys("vanessa.queen@gmail.com");
    driver.FindElement(By.Id("age")).SendKeys("40");
    driver.FindElement(By.Id("experience")).SendKeys("10");
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("phone")).SendKeys("435-678-3213");
    driver.FindElement(By.Id("btnSubmit")).Click();
  }
}
